on:
  rsshub:
    path: /sina/finance
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.rsshub.outputs.title}}
          description: ${{on.rsshub.outputs.description}}
          link: ${{on.rsshub.outputs.link}}
          secret_id: ${{{secrets.SECRET_ID}}
          database_id: ${{secrets.DATABASE_ID}}
        run: | 
          #locale
          #export LANG=zh_CN.UTF-8
          #echo "not using"
          #export LANG=en_US.UTF-8
          #locale
          echo title: $title
          echo description: $description
          echo link: $link
          description_new=`echo $description | sed -e "s/\"/'/g" | sed -e "s/!//g"` 
          echo $description_new
          description1=$(echo $description_new | cut -c1-2000)
          description2=$(echo $description_new | cut -c2001-4000)
          description3=$(echo $description_new | cut -c4001-6000)
          description4=$(echo $description_new | cut -c6001-8000)
          description5=$(echo $description_new | cut -c8001-10000)
          description6=$(echo $description_new | cut -c10001-12000)
          description7=$(echo $description_new | cut -c12001-14000)
          description8=$(echo $description_new | cut -c14001-16000)
          description9=$(echo $description_new | cut -c16001-18000)
          description10=$(echo $description_new | cut -c18001-20000)
          description11=$(echo $description_new | cut -c20001-22000)
          description12=$(echo $description_new | cut -c22001-24000)
          description13=$(echo $description_new | cut -c24001-26000)
          description14=$(echo $description_new | cut -c26001-28000)
          description15=$(echo $description_new | cut -c28001-30000)
          description16=$(echo $description_new | cut -c30001-32000)
          description17=$(echo $description_new | cut -c32001-34000)
          description18=$(echo $description_new | cut -c34001-36000)
          description19=$(echo $description_new | cut -c36001-38000)
          description20=$(echo $description_new | cut -c38001-40000)
          curl  -X POST https://api.notion.com/v1/pages \
                -H "Authorization: Bearer secret_ihJ6bmak2N3lZIZXVgFxEzVSEf3s1iUYUHjTvmaatZ7" \
                -H "Content-Type: application/json" \
                -H "Notion-Version: 2021-08-16" \
                --data "{
                  \"parent\": { \"database_id\": \"d97ed79270b84c2886de539b988d7cb3\" },
                  \"properties\": {
                      \"Title\": {
                          \"type\": \"title\",
                          \"title\": [
                              {
                                  \"type\": \"text\",
                                  \"text\": {
                                      \"content\": \"$title\"
                                  }
                              }
                          ]
                      },
                      \"Description1\": {
                          \"type\": \"rich_text\",
                          \"rich_text\": [
                              {
                                  \"type\": \"text\",
                                  \"text\": {
                                      \"content\": \"${description1}\"
                                  }
                              }
                          ]
                      },
                      \"Description2\": {
                          \"type\": \"rich_text\",
                          \"rich_text\": [
                              {
                                  \"type\": \"text\",
                                  \"text\": {
                                      \"content\": \"${description2}\"
                                  }
                              }
                          ]
                      },
                      \"Description3\": {
                          \"type\": \"rich_text\",
                          \"rich_text\": [
                              {
                                  \"type\": \"text\",
                                  \"text\": {
                                      \"content\": \"${description3}\"
                                  }
                              }
                          ]
                      },
                      \"Description4\": {
                          \"type\": \"rich_text\",
                          \"rich_text\": [
                              {
                                  \"type\": \"text\",
                                  \"text\": {
                                      \"content\": \"${description4}\"
                                  }
                              }
                          ]
                      },
                      \"Description5\": {
                          \"type\": \"rich_text\",
                          \"rich_text\": [
                              {
                                  \"type\": \"text\",
                                  \"text\": {
                                      \"content\": \"${description5}\"
                                  }
                              }
                          ]
                      },
                      \"Description6\": {
                          \"type\": \"rich_text\",
                          \"rich_text\": [
                              {
                                  \"type\": \"text\",
                                  \"text\": {
                                      \"content\": \"${description6}\"
                                  }
                              }
                          ]
                      },
                      \"Description7\": {
                          \"type\": \"rich_text\",
                          \"rich_text\": [
                              {
                                  \"type\": \"text\",
                                  \"text\": {
                                      \"content\": \"${description7}\"
                                  }
                              }
                          ]
                      },
                      \"Description8\": {
                          \"type\": \"rich_text\",
                          \"rich_text\": [
                              {
                                  \"type\": \"text\",
                                  \"text\": {
                                      \"content\": \"${description8}\"
                                  }
                              }
                          ]
                      },
                      \"Description9\": {
                          \"type\": \"rich_text\",
                          \"rich_text\": [
                              {
                                  \"type\": \"text\",
                                  \"text\": {
                                      \"content\": \"${description9}\"
                                  }
                              }
                          ]
                      },
                      \"Description10\": {
                          \"type\": \"rich_text\",
                          \"rich_text\": [
                              {
                                  \"type\": \"text\",
                                  \"text\": {
                                      \"content\": \"${description10}\"
                                  }
                              }
                          ]
                      },
                      \"Description11\": {
                          \"type\": \"rich_text\",
                          \"rich_text\": [
                              {
                                  \"type\": \"text\",
                                  \"text\": {
                                      \"content\": \"${description11}\"
                                  }
                              }
                          ]
                      },
                      \"Description12\": {
                          \"type\": \"rich_text\",
                          \"rich_text\": [
                              {
                                  \"type\": \"text\",
                                  \"text\": {
                                      \"content\": \"${description12}\"
                                  }
                              }
                          ]
                      },
                      \"Description13\": {
                          \"type\": \"rich_text\",
                          \"rich_text\": [
                              {
                                  \"type\": \"text\",
                                  \"text\": {
                                      \"content\": \"${description13}\"
                                  }
                              }
                          ]
                      },
                      \"Description14\": {
                          \"type\": \"rich_text\",
                          \"rich_text\": [
                              {
                                  \"type\": \"text\",
                                  \"text\": {
                                      \"content\": \"${description14}\"
                                  }
                              }
                          ]
                      },
                      \"Description15\": {
                          \"type\": \"rich_text\",
                          \"rich_text\": [
                              {
                                  \"type\": \"text\",
                                  \"text\": {
                                      \"content\": \"${description15}\"
                                  }
                              }
                          ]
                      },
                      \"Description16\": {
                          \"type\": \"rich_text\",
                          \"rich_text\": [
                              {
                                  \"type\": \"text\",
                                  \"text\": {
                                      \"content\": \"${description16}\"
                                  }
                              }
                          ]
                      },
                      \"Description17\": {
                          \"type\": \"rich_text\",
                          \"rich_text\": [
                              {
                                  \"type\": \"text\",
                                  \"text\": {
                                      \"content\": \"${description17}\"
                                  }
                              }
                          ]
                      },
                      \"Description18\": {
                          \"type\": \"rich_text\",
                          \"rich_text\": [
                              {
                                  \"type\": \"text\",
                                  \"text\": {
                                      \"content\": \"${description18}\"
                                  }
                              }
                          ]
                      },
                      \"Description19\": {
                          \"type\": \"rich_text\",
                          \"rich_text\": [
                              {
                                  \"type\": \"text\",
                                  \"text\": {
                                      \"content\": \"${description19}\"
                                  }
                              }
                          ]
                      },
                      \"Description20\": {
                          \"type\": \"rich_text\",
                          \"rich_text\": [
                              {
                                  \"type\": \"text\",
                                  \"text\": {
                                      \"content\": \"${description20}\"
                                  }
                              }
                          ]
                      },
                      \"Url\": {
                          \"type\": \"rich_text\",
                          \"rich_text\": [
                              {
                                  \"type\": \"text\",
                                  \"text\": {
                                      \"content\": \"$link\"
                                  }
                              }
                          ]
                      }
                  }
                }"
          echo 'finished'
