on:
  rsshub:
    path: /sina/finance
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.rsshub.outputs.title}}
          description: ${{on.rsshub.outputs.description}}
          link: ${{on.rsshub.outputs.link}}
          secret_id: ${{{secrets.SECRET_ID}}
          database_id: ${{secrets.DATABASE_ID}}
        run: | 
          echo title: $title
          echo description: $description
          echo link: $link
          curl  -X POST https://api.notion.com/v1/pages \
                -H "Authorization: Bearer secret_ihJ6bmak2N3lZIZXVgFxEzVSEf3s1iUYUHjTvmaatZ7" \
                -H "Content-Type: application/json" \
                -H "Notion-Version: 2021-08-16" \
                --data "{
                  \"parent\": { \"database_id\": \"d97ed79270b84c2886de539b988d7cb3\" },
                  \"properties\": {
                      \"Title\": {
                          \"type\": \"title\",
                          \"title\": [
                              {
                                  \"type\": \"text\",
                                  \"text\": {
                                      \"content\": \"$title\"
                                  }
                              }
                          ]
                      },
                      \"Description\": {
                          \"type\": \"rich_text\",
                          \"rich_text\": [
                              {
                                  \"type\": \"text\",
                                  \"text\": {
                                      \"content\": \"$description\"
                                  }
                              }
                          ]
                      },
                      \"Url\": {
                          \"type\": \"rich_text\",
                          \"rich_text\": [
                              {
                                  \"type\": \"text\",
                                  \"text\": {
                                      \"content\": \"$link\"
                                  }
                              }
                          ]
                      }
                  }
                }"

          echo "{
            \"parent\": { \"database_id\": \"d97ed79270b84c2886de539b988d7cb3\" },
            \"properties\": {
                \"Title\": {
                    \"type\": \"title\",
                    \"title\": [
                        {
                            \"type\": \"text\",
                            \"text\": {
                                \"content\": \"$title\"
                            }
                        }
                    ]
                },
                \"Description\": {
                    \"type\": \"rich_text\",
                    \"rich_text\": [
                        {
                            \"type\": \"text\",
                            \"text\": {
                                \"content\": \"$description\"
                            }
                        }
                    ]
                },
                \"Url\": {
                    \"type\": \"rich_text\",
                    \"rich_text\": [
                        {
                            \"type\": \"text\",
                            \"text\": {
                                \"content\": \"$link\"
                            }
                        }
                    ]
                }
            }
          }"
          echo 'finished'
