on:
  rsshub:
    path: /zhihu/hotlist
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.rsshub.outputs.title}}
          description: ${{on.rsshub.outputs.description}}
          link: ${{on.rsshub.outputs.link}}
          pubDate: ${{on.rsshub.outputs.pubDate}}
          secret_id: ${{secrets.SECRET_ID}}
          database_id: ${{secrets.DATABASE_ID}}
        run: | 
          echo title: $title
          echo description: $description
          echo link: $link
          description_new=`echo $description | sed -e "s/\"/'/g" | sed -e "s/!//g"` 
          current_time=`date +'%Y-%m-%d %H:%M:%S'`
          echo $description_new
          echo 'finished'
